### ISSUE TITLE
Send file uri in reqmode

### ISSUE THREAD

**Issue by mishalll** [nathan242/php-icap-client#1]
How can I send file uri in reqmode - request for icam-server?
I also saw an icap standart [rfc3507](https://datatracker.ietf.org/doc/html/rfc3507#section-4.8.1)

For example php-code

```
print_r(
        $icap->reqmod(
            'example',
            [
                'req-hdr' => "POST /icap_client/test_files/clientjavascript.chm HTTP/1.1\r\nHost: 10.168.30.128\r\n\r\n",
                'req-body' => 'This is test 1.'
            ]
        )
    );
```

return

```
Array
(
    [protocol] => Array
        (
            [icap] => ICAP/1.0
            [code] => 200
            [message] => ok
        )

    [headers] => Array
        (
            [Server] => InfoWatch ICAP server
            [X-Include] =>  X-Client-IP, X-Server-IP
            [Connection] => close
            [Encapsulated] => req-hdr=0, req-body=84
        )

    [body] => Array
        (
            [req-hdr] => POST /icap_client/test_files/clientjavascript.chm HTTP/1.1
Host: 10.168.30.128
            [req-body] => This is test 1.
        )

    [rawBody] => POST /icap_client/test_files/clientjavascript.chm HTTP/1.1
Host: 10.168.30.128

f
This is test 1.
0


)
```

**Comment by nathan242** [comment]
Can you give me more detail on what you are trying to do?

If you are trying to scan a file for viruses via ICAP you will need to pass the file content in the 'req-body' parameter. Blocked content won't be returned in the ICAP response and there may be details in the response headers.

**Comment by mishalll** [comment]
Thanks for reply. In rfc3507 I saw.

> 4.2  ICAP URIs
> 
>    All ICAP requests specify the ICAP resource being requested from the
>    server using an ICAP URI.  This MUST be an absolute URI that
>    specifies both the complete hostname and the path of the resource
>    being requested.

But do you mean insert to [req-body] blob-content of checking file, right? In that case how can I send to icam-server the file-name? Do you have some examples to check pdf, jpg, docx and other non-text files?

**Comment by nathan242** [comment]
The ICAP URI is built from the host address (as passed into the class constructor) and the service name that you pass as the first parameter to reqmod(). The URI will be "icap://\<host\>/\<service\>".

When I have used an ICAP server in the past to virus scan files I only had to send the file blob as the req-body. If you want to send the filename you may need to pass it in a HTTP request header in req-hdr. You may need to check the documentation for the ICAP server you are using.

**Comment by mishalll** [comment]
Do you have some examples for req-body and req-hdr?

**Comment by pavelkrustev** [comment]
If it could be of any help to somebody here is my trial-and-error code proved to be working OK with my ICAP service (c-icap instance):

```
    echo "===========================================================\n\n\n";

   $testedfile =  file_get_contents('virus/Eicar-Test-Signature.zip');

    print_r(
        $icap->reqmod(
            'squidclamav',
            [
                'req-hdr' => "POST /test HTTP/1.1\r\nHost: 127.0.0.1\r\n\r\n",
                'req-body' => $testedfile
            ]
        )
    );
```


Here is the output:


```
===========================================================


Array
(
    [protocol] => Array
        (
            [icap] => ICAP/1.0
            [code] => 200
            [message] => OK
        )

    [headers] => Array
        (
            [Server] => C-ICAP/0.5.6
            [Connection] => close
            [ISTag] => CI0001-1-squidclamav-10
            [X-Virus-ID] => Eicar-Signature
            [X-Infection-Found] => Type=0; Resolution=2; Threat=Eicar-Signature;
            [Encapsulated] => res-hdr=0, res-body=343
        )

    [body] => Array
        (
            [res-hdr] => HTTP/1.0 307 Temporary Redirect
Location: http://proxy.domain.dom/cgi-bin/clwarn.cgi?url=/test&source=-&user=-&virus=stream: Eicar-Signature FOUND&recover=(null)
Server: C-ICAP
Connection: close
Content-Type: text/html
Content-Language: en
X-Virus-ID: Eicar-Signature
X-Infection-Found: Type=0; Resolution=2; Threat=Eicar-Signature;
            [res-body] => 
        )

    [rawBody] => HTTP/1.0 307 Temporary Redirect
Location: http://proxy.domain.dom/cgi-bin/clwarn.cgi?url=/test&source=-&user=-&virus=stream: Eicar-Signature FOUND&recover=(null)
Server: C-ICAP
Connection: close
Content-Type: text/html
Content-Language: en
X-Virus-ID: Eicar-Signature
X-Infection-Found: Type=0; Resolution=2; Threat=Eicar-Signature;

0


)
```
